### ISSUE TITLE
find is not working

### ISSUE THREAD

**Issue by railsmechanic** [Softmotions/ejdb-ruby#1]
I've successfully installed the ejdb ruby bindings according to the installation guide.
Creating a new database/collection works, but when I try to execute the "One snippet intro" the following exception is raised when it comes to find the data:

```
results = jb.find("parrots", {"likes" => "toys"}, {"$orderby" => {"name" => 1}})
TypeError: wrong argument type Hash (expected Data)
```

The same exception is raised with ```find_one```

Here's my setup:

- Mac OS X 10.8.5
- Ruby 2.0 p247
- Installed ejdb via homebrew (v1.1.24)

**Comment by urma** [comment]
I have a very similar setup:
* Mac OS X 10.10.2
* ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.1.0] (installed via ``rvm``)
* ejdb: stable 1.2.5 (installed via homebrew)

``make check`` returns the following:
```
$ make check
make -C ./test
ruby t1.rb
t1.rb:37:in `find': wrong argument type Hash (expected Data) (TypeError)
	from t1.rb:37:in `<main>'
make[1]: *** [check] Error 1
make: *** [check] Error 2
```
